<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Rohith's portfolio</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width">

<link rel="stylesheet" href="index/css/bootstrap.min.css">
<style>
body {
	padding-top: 60px;
	padding-bottom: 40px;
}

.content {
background-color: lightblue;
display: block;
margin-left:auto;
margin-right: auto;
}

</style>
<link rel="stylesheet" href="index/css/bootstrap-responsive.min.css">
<link rel="stylesheet" href="index/css/main.css">

<script src="index/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>
</head>
<body>
	<!--[if lt IE 7]>
            <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
        <![endif]-->

	<!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->

	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a class="brand" href="#">Rohith Nair</a>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li class="active"><a href="#">Home</a></li>
						
						<!--  <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li> -->
					</ul>
					<!-- <form class="navbar-form pull-right">
                            <input class="span2" type="text" placeholder="Email">
                            <input class="span2" type="password" placeholder="Password">
                            <button type="submit" class="btn">Sign in</button>
                        </form> -->
				</div>
				<!--/.nav-collapse -->
			</div>
		</div>
	</div>

	<div class="container">

		<!-- Main hero unit for a primary marketing message or call to action -->
		<!-- 
            <div class="hero-unit">
                <h1>Hello, world!</h1>
                <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
                <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
            </div>
			 -->

		<div class="row">
			<div class="span6">
				<h2>Portfolio site</h2>
				

			</div>
		</div>

		<!--    
         <div class="span2">
                <div class="span14">
                    <h2>Project Summary</h2>
                    <p>A project summary</p>
                </div>
                </div> 
                
                -->

		<div class="tabbable tabs-right">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#edu" data-toggle="tab">Educational
						Background</a></li>
				<li><a href="#currProj" data-toggle="tab">My Projects</a></li>
				<li><a href="#techInterest" data-toggle="tab">Technology Interests</a></li>
				<li><a href="#empHistory" data-toggle="tab">Employment History</a></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="edu">
					<table class="table table-bordered">
						<thead>
							<tr>
								<th>No</th>
								<th>Institution</th>
								<th>Degree</th>
								<th>Qualification</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>1</td>
								<td>Henley Business School, UK</td>
								<td>Msc Business Information Management</td>
								<td>Expected: Pass with Merit</td>
							</tr>
							<tr>
								<td>2</td>
								<td>Amrita School of Engineering, India</td>
								<td>Btech Computer Science</td>
								<td>First class</td>
							</tr>
							<tr>
								<td>3</td>
								<td>Technical Higher Secondary School, India</td>
								<td>Biology</td>
								<td>Distinction</td>
							</tr>
							<tr>
						
						</tbody>
					</table>
				</div>
				<div class="tab-pane" id="currProj">

					<div class="accordion" id="accordion2">
						<div class="accordion-group">
							<div class="accordion-heading">
								<a class="accordion-toggle" data-toggle="collapse"
									data-parent="#accordion2" href="#collapseOne"> SSMEnet Service
									Innovation </a>
							</div>
							<div id="collapseOne" class="accordion-body collapse in">
								<div class="accordion-inner">
									This project is aimed at innovating the current SSMEnet website
									to enable a high level of collaboration.<br /> This is done as
									a part of the Msc Business Information Management dissertation.
									The project focus was in innovating the knowledge management
									activities occuring inside the SSMEnet community using Web 2.0
									tools. A new set of service blue prints were generated for the
									innovation purpose. <br /> 
									<br/>
									
									Please find the dissertation below :
									<br/><br/>
									<iframe src="https://docs.google.com/file/d/0BzS5KDklAA0yWGFfbjBHYVNtdW8/preview" width="640" height="480"></iframe>

								</div>
							</div>
						</div>
						<div class="accordion-group">
							<div class="accordion-heading">
								<a class="accordion-toggle" data-toggle="collapse"
									data-parent="#accordion2" href="#collapseTwo"> Map4Map Mobile
									App </a>
							</div>
							<div id="collapseTwo" class="accordion-body collapse">
								<div class="accordion-inner">
									<b>Map4Map</b> is a smart phone app that helps you keep your
									loved ones in a pre-defined route. This is done for my
									employer, AVA solutions. <br /> The application is developed
									using Windows Phone 7.5 and you can visit <a
										href="http://map4map.com">http://map4map.com</a> to download
									it. <br /> <br />
									<p>Below you can find the demo about the application.</p>

									<iframe class="youtube-player" width="640" height="385"
										src="http://www.youtube.com/embed/ChDR1Nxx9Zg"> </iframe>
								</div>
							</div>
						</div>

						<div class="accordion-group">
							<div class="accordion-heading">
								<a class="accordion-toggle" data-toggle="collapse"
									data-parent="#accordion2" href="#collapseThree"> C++ Tutorial website </a>
							</div>
							<div id="collapseThree" class="accordion-body collapse">
								<div class="accordion-inner">

									<p><b>C++ tutorial website</b> is aimed at higher secondary and
										undergraduate students who are learning C++.</p>

									<br /> The site was developed as a learning tool while I was
									studying in my high school. All the programs are organised
									based on the difficulty level and I have received appreciation
									for my work. 
									<br/><br/>
									Testimonials include: <br />  
			
									<i>
									"Rohith,
									your website  is very much useful for me. Hat off. I asked my students
									to refer you website for oops programming especially overloading
									concept."  - Satyabhama / Professor-Anna university Chennai 
									</i>
									
									<br/><br/>
									PS: This website is not currently maintained.

									<br/><br/> You can refer the site at : <a href="http://rohithr.8m.com/">Turbo C++ tutorial website</a>
								</div>
							</div>
						</div>
						
						
							<div class="accordion-group">
							<div class="accordion-heading">
								<a class="accordion-toggle" data-toggle="collapse"
									data-parent="#accordion2" href="#collapseFour"> Cloud Application development </a>
							</div>
							<div id="collapseFour" class="accordion-body collapse">
								<div class="accordion-inner">

								 <p>Recently, I have been trying my hands on SaaS and PaaS based application delivery models.</p>
								 
								 As a part of learning new technologies, currently I am maintainng this portfolio website which is developed using 
								 PhpCloud, a SaaS offering from Zend.
								
								<br/><br/> You can find the repository at <a href="">GitHub</a>
									 
								</div>
							</div>
						</div>
						

					</div>

				</div>
				<div class="tab-pane" id="empHistory">
				 <ul class="nav nav-tabs" id="myTab">
			  <li class="active"><a href="#ava" data-toggle="tab">AVA Solutions</a></li>
			  <li><a href="#infosys" data-toggle="tab">Infosys Technologies Limited</a></li>
			   
			</ul>
			 
			<div class="tab-content">
			  <div class="tab-pane active" id="ava">
			  <p class="content"><b>Part-time Software Developer Novemebr 2011 - Present</b></p><br/>
			  <ul class="nav nav-list">
			  <li><i class="icon-ok"></i>Designed , developed, unit-tested calendar web application in ASP.NET C# 4.0 for agency software
				which helps in scheduling work timing for &nbsp;&nbsp;agency workers.</li> 
				<br/>
				<li><i class="icon-ok"></i>Created, modified and tested stored procedures compliant to SQL Server 2005 for backward
				compatibility of agency software.</li>
				<br/>
				<li><i class="icon-ok"></i>
				Currenlty developing Map4Map Windows Phone Mango mobile application to help parents and care-takers
				track their child. </li>
			  </ul>
			  </div>
		<div class="tab-pane fade" id="infosys">
		  <p class="content"><b>Full-time Systems Engineer January 2009 - September 2011</b></p>
			 <ul class="nav nav-list">
			<br/>
			<li><i class="icon-ok"></i> Designed , developed, unit-tested and maintained 14 SQL Server Reporting Services (SSRS) report
		by writing SQL and Oracle queries/ procedures and functions for displaying in web application.</li>
		<br/>
		<li><i class="icon-ok"></i>Verified query performance in running report queries using query plans and SQL Server Profiler.</li>
		<br/>
		<li><i class="icon-ok"></i>Implemented server-side communication code in reporting module for liaising with SOAP web
		service from Emergency Alert System JEE code</li>
		<br/>
		<li><i class="icon-ok"></i>Undertook maintenance of database migration project for staging Oracle tables to Microsoft SQL
		technology using SSIS for reporting module, which was initially handled by onsite-team. </li>
		<br/>
		<li><i class="icon-ok"></i>Pro-actively monitored the HP- Bug ticketing software - HP Quality Center for incoming bugs which
		helped Infosys to meet SLA in stipulated time-frame.</li>
		
		</ul>
		</div>
			</div>
			 
			<script>
			  $(function () {
				  $('#myTab a').click(function (e) {
					  e.preventDefault();
					  $(this).tab('show');
			  });
			</script>
				</div>
				
				<div class="tab-pane" id="techInterest">
				
				<table class="table table-striped table-bordered table-condensed">
			 <thead>
        		<tr>
        
		            <th>Beginner</th>
		            <th>Intermediate</th>
		            <th>Advanced</th>
        		</tr>
        
    		</thead>
		    		<tbody>
		        <tr>
		            
		            <td>JEE</td>
		            <td>C</td>
		            <td>C#</td>
		        </tr>
		        <tr>
					<td>SSIS</td>
					<td>C++</td>
					<td>ASP.NET 3.5,4.0</td>
				</tr>
				<tr>
					<td>Windows Phone 7.5</td>
					<td>Core Java</td>
					<td>Web services</td>
				</tr>
				<tr>
					<td>Git</td>
				    <td>Oracle 8i</td>
				    <td>SSRS 2008</td>
				 </tr>
				
				<tr>
					<td>HP Quality Center</td>
					<td>JQuery</td>
					<td>SQL Server 2008</td>
				</tr>
				
				<tr>
					<td>Oracle Map Viewer</td>
					<td>Visual Source Safe</td>
					<td>HTML 4 and 5</td>
				<tr>
					<td>Microsoft Map Tools, VEserver</td>
					<td>Microsoft Office Tools</td>
					<td>CSS</td>
				</tr>
				<tr>
					<td>LINQ</td>
					<td></td>
		            <td>Windows Phone 7.5</td>
		       </tr>
		        <tr>
		 		<td>
		 		</td>
		 		<td></td>
				<td>Visual Studio 2008</td>
		        </tr>

		    </tbody>
    		
    </table>
				
				
				
				
				</div>
				
				
			</div>

		</div>
		<!-- /tabbable -->


		<!--  
                <div class="span4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
               </div>
                <div class="span4">
                    <h2>Heading</h2>
                    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
                </div>
           
            -->




		<hr>



	</div>
	<!-- /container -->
	<footer><i>Copyright &copy; Rohith Nair. Site template used: Twitter Bootstrap.</i></footer>
	<script
		src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="index/js/vendor/jquery-1.8.0.min.js"><\/script>')</script>

	<script src="index/js/vendor/bootstrap.min.js"></script>

	<script src="index/js/main.js"></script>
</body>
</html>
